"""Testing migrations: new column in users table, added organization type

Revision ID: 819d277ca7ad
Revises: 
Create Date: 2019-12-10 00:20:20.817930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819d277ca7ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_org', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_org')
    # ### end Alembic commands ###
